from fastapi import FastAPI, UploadFile, File ,HTTPException
from fastapi.responses import JSONResponse
from starlette.status import HTTP_404_NOT_FOUND,HTTP_400_BAD_REQUEST
from pydantic import BaseModel 
from functions_carri import *
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="Predict API", version="1.0.0")



class QUESTION_Request(BaseModel):
    question: str


# API_KEY="API-KEY-HERE- :D"  ## Don't forget API key :) 
# LLM_URL="https://tokenfactory.esprit.tn/api"
PORT=7777   ## ista3mil el port hada fi el ngrok




class FileRequest(BaseModel):
    """
    Request model for storing a file.
    """
    message:str
    file_name: str
    file_content: bytes


import base64


@app.post("/lung_predict")
async def lung_predict(file_request: FileRequest):
    """
    Endpoint that stores a file sent through a POST request.
    """
    try:
        
        print(file_request.message)
        file_path = os.path.join(r".\uploads\lung\uploaded_files", file_request.file_name)
        file_bytes = base64.b64decode(file_request.file_content)
        with open(file_path, "wb") as f:
            f.write(file_bytes)
        
        response = predict_and_display(file_path)
        
        print(response) 
        return JSONResponse(content={ 
                "answer": response
            })
    except Exception as e:
        return JSONResponse(content={"error": str(e)}, status_code=400)

# prediction, probability = predict_single_image(
#     r"./envoyer\caries\4d0705fb-FA0235.jpg", 
#     vae, 
#     clf, 
#     device
# )

@app.post("/carrie_predict")
async def lung_predict(file_request: FileRequest):
    """
    Endpoint that stores a file sent through a POST request.
    """
    try:
        
        print(file_request.message)
        file_path = os.path.join(r".\uploads\carrie\uploaded_files", file_request.file_name)
        file_bytes = base64.b64decode(file_request.file_content)
        with open(file_path, "wb") as f:
            f.write(file_bytes)
        
        response = predict_single_image(
            file_path, 
            vae, 
            clf, 
            device
        )
        
        print(response) 
        return JSONResponse(content={ 
                "answer": response
            })
    except Exception as e:
        return JSONResponse(content={"error": str(e)}, status_code=400)





# CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# import httpx
# from openai import OpenAI

# http_client = httpx.Client(verify=False) # Désactive la vérification du certificat TLS/SSL



# client = OpenAI(
#     api_key=API_KEY,
#     base_url=LLM_URL,
#     http_client=http_client
# )



# def query_LLM(sys_prompt,prompt):
  
#     """
#     Query the LLM to generate an answer based on the given system prompt and user prompt.

#     Args:
#         sys_prompt (str): The system prompt to use for generating the answer.
#         prompt (str): The user prompt to use for generating the answer.

#     Returns:
#         str: The generated answer from the LLM.

#     """
#     print(sys_prompt)
#     print(prompt)
#     response = client.chat.completions.create(
#         model="hosted_vllm/Llama-3.1-70B-Instruct",
#         messages=[
#             {"role": "system", "content": sys_prompt},
#             {"role": "user", "content": prompt}
#         ],
#         temperature=0.7,
#         max_tokens=1000,
#         top_p=0.9,
#         frequency_penalty=0.0,
#         presence_penalty=0.0
#     )

#     print(response.choices[0].message.content)
#     return response.choices[0].message.content



# @app.post("/llm")
# async def LLM(question_request: QUESTION_Request):
#     """
#     LLM (Language Model) endpoint. This endpoint takes a question in the request body
#     and returns an answer generated by the LLM.

#     Args:
#         question_request: QUESTION_Request object containing the question to be answered.

#     Returns:
#         A JSON response containing the answer to the question.

#     Raises:
#         HTTPException: If there is an error in generating the answer.
#     """
#     try:
#         #### make sure bich tbaddel el system wo user prompt kima t7ib 
#         system_prompt="""you are a medical chatbot .  
#         you will be given some question and you will give an answer to it. 
#         use the given context to answer the question.
#         """
#         #### #### #### #### #### #### #### #### #### #### #### #### #### 
#         user_prompt=f"""question:
#         {question_request.question} 
#         """
#         #### #### #### #### #### #### #### #### #### #### #### #### #### 

#         answer=query_LLM(system_prompt,user_prompt)
#         return{"answer":answer}

#     except Exception as e:
#         print(e)
#         raise HTTPException(
#             status_code=HTTP_400_BAD_REQUEST,
#             detail=f"error: {str(e)}"
#         )
    




import uvicorn

if __name__ == "__main__":
    uvicorn.run(
        app, 
        host="0.0.0.0",
        port=PORT
    )


